PF_17.1 dialog modal to request goal for a new simulation
Bootcamp2020/skillful_network pull request #133
Opened 2020-04-08 13:28 UTC by pfouque06

2020-04-08 14:32 UTC, danglotb commented on skillful_network_client/src/app/home/dashboard/simulation/goal-validation-modal/goal-validation-modal.component.html
> +    <!-- <p>What's your email?</p> -->
Supprimer les commentaires

2020-04-08 14:32 UTC, danglotb commented on skillful_network_client/src/app/home/dashboard/simulation/goal-validation-modal/goal-validation-modal.component.html
> +    <!-- <button mat-button [mat-dialog-close]="data.email" cdkFocusInitial>Yes</button> -->
Idem

2020-04-08 14:32 UTC, danglotb commented on skillful_network_client/src/app/home/dashboard/simulation/goal-validation-modal/goal-validation-modal.component.ts
> +    //@Inject(MAT_DIALOG_DATA) public data: DialogData) {
Supprimer les commentaires

2020-04-08 14:33 UTC, danglotb commented on skillful_network_client/src/app/home/dashboard/simulation/simulation.component.html
> +            <!-- <mat-progress-spinner class="is-loading" mode="indeterminate"></mat-progress-spinner> -->
Supprimer les commentaires

2020-04-08 14:34 UTC, danglotb commented on skillful_network_client/src/app/shared/models/simulation.ts
> +        if (data == null) {
À quoi sert le `then` de ce `if` ?

2020-04-08 14:36 UTC, danglotb requested changes
- Suppression des commentaires d'anciens codes.
 - Il y a pas mal de `console.log` dans tes changements, je me demande si ça va pas trop spammer la console.

2020-04-08 15:01 UTC, pfouque06 commented on skillful_network_client/src/app/shared/models/simulation.ts
> +        if (data == null) {
je m'en suis servi pour créer une Simulation "vide" sachant qu'à priori il n'est poassible d'avoir plusierus constructeurs ..
Je pense qu'on peut l'enlever mais ça peut-être être utile en tant que pre-check avant de passer au else si jamais data est null ....
A toi de me dire

2020-04-08 15:03 UTC, pfouque06 commented
>     * Suppression des commentaires d'anciens codes.
> 
>     * Il y a pas mal de `console.log` dans tes changements, je me demande si ça va pas trop spammer la console.

Les log m'ont permit de tracer pendant le dev bien sûr, on peut en retirer une partie ou tout..
A toi de me dire

2020-04-09 09:49 UTC, danglotb commented on skillful_network_client/src/app/shared/models/simulation.ts
> +        if (data == null) {
Tu peux le retirer je pense.

2020-04-09 10:15 UTC, danglotb approved these changes

2020-04-09 10:20 UTC, merged