Mg 3.r.2 a liaison back front offre formation
Bootcamp2020/skillful_network pull request #140
Opened 2020-04-09 09:07 UTC by glawdysMona

Liaison back front pour la page liste de formation et création du composant générique pour les page liste des utilisateurs, liste des offres d'emplois, et liste de formation.

2020-04-09 12:03 UTC, danglotb commented on skillful_network_client/src/app/home/formation-list/formation-list.component.ts
> +  constructor() {
Est-ce que ce component est encore utilisé ? Il est complètement vide et semble ne rien faire. Peux-t-on le supprimer ?

2020-04-09 12:04 UTC, danglotb commented on skillful_network_client/src/app/shared/services/training.service.ts
> +    //     this.trainings = [];
Si on a plus besoin de ce code, on le supprime. Garder du vieux code commenté pollue le code.

2020-04-09 12:06 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/security/BasicAuthConfiguration.java
> +//@EnableGlobalMethodSecurity(prePostEnabled = true)
On ne va pas ajouter cette modification au dépôt distant.

2020-04-09 12:08 UTC, danglotb requested changes
Génial ! Juste quelques changements requis avant de merge. Voir les commentaires dans le code.

2020-04-09 13:41 UTC, glawdysMona commented on skillful_network_client/src/app/home/formation-list/formation-list.component.ts
> +  constructor() {
Il me semble qu'il ne faut pas le supprimer c'est lui qui donne le selector , c'est le coeur du component

2020-04-09 13:41 UTC, glawdysMona commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/security/BasicAuthConfiguration.java
> +//@EnableGlobalMethodSecurity(prePostEnabled = true)
ok je modifie

2020-04-10 08:15 UTC, danglotb approved these changes

2020-04-10 10:29 UTC, danglotb approved these changes

2020-04-10 11:33 UTC, merged