Feature/sh manage jwt provider exceptions
Bootcamp2020/skillful_network pull request #143
Opened 2020-04-09 11:16 UTC by Samuel-Huguet

2020-04-09 11:44 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtAuthTokenFilter.java
> +			return jwt.equals("") ? null : jwt;
Remplacer `jwt.equals("")` par `jwt.isEmpty()`

2020-04-09 11:47 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +	private static final String SCRIPT_URL = Paths.get("src/main/resources/data/script/scriptToken.py").toAbsolutePath()
Cette façon de récupérer le chemin du script ne s'adapte pas à toutes les configurations, _e.g.._ chez moi ça ne fonctionne pas. 

On peut s'inspirer de ce qui est fait dans [fr.uca.cdr.skillful_network.tools.json.JSONLoader](https://github.com/danglotb/skillful_network/blob/develop/skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/tools/json/JSONLoader.java#L64) :
```java
final String resourceDir = this.getClass().getResource("/").getPath();
final String cwdDirectory = resourceDir.substring(0, resourceDir.lastIndexOf(SKILLFUL_NETWORK_SERVER_PATH));
final String url = cwdDirectory + SKILLFUL_NETWORK_SERVER_PATH + this.path;
```

2020-04-09 11:47 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +	private String PY_CMD;
Nice one !

2020-04-09 11:52 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +			p.destroy();
Il faut `destroy()` et `close()` dans un block `finally` car si une erreur apparait avant, le `Process` et le `BufferedReader` ne seront pas détruit et fermé respectivement.

On pourrait utiliser un try/catch with resource pour le BufferedReader, _c.f._ [this](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

2020-04-09 11:52 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +			while ((line = in.readLine()) != null) {
On pourrait adapter le code du `while` en Java 8 style, mais c'est du sucre syntaxique. (optionnel)

2020-04-09 11:54 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +			BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
On peut récupérer aussi le `getErrorStream()` du `Process p` pour afficher le `stderr` du script python sur le `System.err` du back.

2020-04-09 11:55 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +		if (scriptResponse.equals("-4")) {
On pourrait faire un `switch/case` sur les codes.

On pourrait aussi encapsuler les codes et les messages d'erreurs et rendre ça un peu plus objet et automatique.

2020-04-09 11:56 UTC, danglotb requested changes
Deux changements sont nécessaires : 
1. Le calcul du path du script
2. le `destroy()` et le `close()` dans un block `finally`.

Le reste c'est de l'amélioration de code et reste optionnel.

2020-04-10 15:08 UTC, DamienMonchaty approved these changes

2020-04-10 15:10 UTC, Samuel-Huguet commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +	private static final String SCRIPT_URL = Paths.get("src/main/resources/data/script/scriptToken.py").toAbsolutePath()
J'ai mis une solution en place, il faut tester si ça marche bien pour tout le monde.

2020-04-10 15:10 UTC, DamienMonchaty approved these changes

2020-04-10 15:12 UTC, Samuel-Huguet commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/jwt/JwtProvider.java
> +		if (scriptResponse.equals("-4")) {
Je n'ai pas encore mis en place le switch ni l'encapsulation. Je ne vois pas trop ce que tu entends pas là, tu pourrais me donner un peu plus de détails stp ?

2020-04-10 15:14 UTC, DamienMonchaty approved these changes

2020-04-10 18:28 UTC, merged