AA_10.2.2.3 v1.0 [UserController,UserService,UserServiceImpl] ajout d…
Bootcamp2020/skillful_network pull request #23
Opened 2020-03-23 15:33 UTC by anaKnell

…'un système de pagination de la liste utilisateur méthode @GetMapping

2020-03-23 15:50 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +	@GetMapping(value = "users/{page}")
Ici, tu remplaces carrément le `getUsers()` (donc tous les utilisateurs) par le `getUsers(page)` (donc les utilisateurs d'une page. Je pense que l'on devrait garder le `getUsers()`.

Le mapping sur `/users/{page}`, pour rester cohérent avec l'ensemble bien que Spring va l'ajouter automatiquement.

Je me demande si on aura un soucis de résolution avec le mapping `value = "/users/{id}"`, malgré la surcharge des paramètres.

2020-03-23 15:50 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +	public ResponseEntity<Page<User>> getU(@PathVariable(value = "page") int pageNumber) {
Renommer la méthode pour donner clairement l'intention de la méthode. `getU` n'est pas assez explicite.

2020-03-23 15:51 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +		else {
on va préféré l'écriture suivante : 
```java
} else {
```

2020-03-23 15:54 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +		Pageable pageable = PageRequest.of(pageIndex, 10);
Ici, on fixe la taille de la page en dur dans le code de la méthode. On pourrait le rendre réutilisable peut-être ce code. Imaginons qu'un administrateur veuille accéder à cette liste et souhaiterais une plus longue liste (100 éléments par exemple).

Je pense qu'il serait bien d'implémenter la logique dans le service plutôt que directement dans le contrôleur. On éviterait ainsi l'accès direct au repository depuis le contrôleur, mais plutôt passer par le service.

2020-03-23 15:55 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +		return new ResponseEntity<>(listUserByPage, HttpStatus.OK);
Est-ce que le frontend est capable de gérer les Object `Page<User>` ?

2020-03-23 15:56 UTC, danglotb requested changes
Le plus gros serait factorisé la logique de pagination et de la rendre réutilisable ainsi que de la déplacer dans le Service plutôt que dans le Contrôleur.

2020-03-23 19:25 UTC, anaKnell commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +	@GetMapping(value = "users/{page}")
commit 18efd5d99a8b72b2033ab3b0849085c53f24adeb:
* Reinsertion getUsers()
* modification de la value GetMapping "/users" : effectivement soucis avec le mapping @GetMapping

2020-03-23 19:26 UTC, anaKnell commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +	public ResponseEntity<Page<User>> getU(@PathVariable(value = "page") int pageNumber) {
commit 18efd5d99a8b72b2033ab3b0849085c53f24adeb:
* Modification : erreur durant la sauvegarde -> getUsersPerPage()

2020-03-23 19:27 UTC, anaKnell commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +		else {
commit 18efd5d:
* modification

2020-03-23 19:29 UTC, anaKnell commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +		Pageable pageable = PageRequest.of(pageIndex, 10);
commit 18efd5d:
* ajout méthode Pageable dans UserService requestPage(int objPerPage, int pageIndex);utilisable pour toute entité. Modification du nombre de page et du nombre d'entités par page

2020-03-24 08:45 UTC, danglotb approved these changes

2020-03-24 12:22 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> -	@GetMapping(value = "/users")
Du coup, on ne peut pas recupérer simplement la liste des utilisateurs ?

2020-03-24 12:22 UTC, danglotb commented on skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/UserController.java
> +	public ResponseEntity<Page<User>> getUsersPerPage(@RequestParam("nbr") int nbr, @RequestParam("page") int page){
Pourront-on mettre des valeurs par défaut ?

2020-03-25 09:33 UTC, merged