Feature/mg 10.2.1 création de laffichage des utilisateurs
Bootcamp2020/skillful_network pull request #30
Opened 2020-03-25 11:23 UTC by glawdysMona

Partie non terminée de la page de la liste des utilisateurs (il reste la mise en forme et le format de date à modifier)

2020-03-25 13:59 UTC, danglotb commented on skillful_network_client/src/app/shared/services/user.service.ts
> +  return this.users[id];
Mauvaise indentation

2020-03-25 14:01 UTC, danglotb commented on skillful_network_client/src/app/shared/models/user.ts
> +    this.birthDate= data.birthDate;
Ta ligne `this.birthDate= data.birthDate;` est dupliquée avec la [Ligne 27](https://github.com/danglotb/skillful_network/blob/develop/skillful_network_client/src/app/shared/models/user.ts#L27).

2020-03-25 14:02 UTC, danglotb commented on skillful_network_client/src/app/shared/services/user.service.ts
> +  public getAllUser():Promise<any>{
Cette méthode resemble étrangement à `findAll(): Promise<User[]>`.
Il semblerait que `findAll()` n'est pas été implémentée. Je propose de soit supprimé `findAll(): Promise<User[]>` soit bouger l'implémentation de `getAllUser()` dans `findAll(): Promise<User[]>` et supprimer `getAllUser()`,

2020-03-25 14:03 UTC, danglotb commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +        -->
Supprimer les commentaires inutiles.

2020-03-25 14:03 UTC, danglotb commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +</div>-->
Idem.

2020-03-25 14:05 UTC, danglotb commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +              <mat-cell *matCellDef="let user"> <a [routerLink]="['/home/user-list/'+user.id]" ><img src="../../../assets/pictures/Oeil-details.svg"></a> </mat-cell>
Je ne suis pas pour uploaded nos propres icons. Pourrait-on utiliser une icon de material comme il est fait pour les icons de la configuration du profil dans [user-conf.component.ts](https://github.com/danglotb/skillful_network/blob/develop/skillful_network_client/src/app/home/profile-conf/user-conf/user-conf.component.html#L15) ?

2020-03-25 14:08 UTC, danglotb requested changes
1. Voir pour mettre une icons Material plutôt qu'uploader la notre.
2. Gérer les signatures de méthodes redondantes.
3. Clean code : indentation, affectation redondante et commentaires.

2020-03-25 15:19 UTC, glawdysMona commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +              <mat-cell *matCellDef="let user"> <a [routerLink]="['/home/user-list/'+user.id]" ><img src="../../../assets/pictures/Oeil-details.svg"></a> </mat-cell>
J'ai modifié

2020-03-25 15:19 UTC, glawdysMona commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +</div>-->
J'ai modifié

2020-03-25 15:20 UTC, glawdysMona commented on skillful_network_client/src/app/home/users-list/users-list.component.html
> +        -->
J'ai modifié

2020-03-25 15:20 UTC, glawdysMona commented on skillful_network_client/src/app/shared/services/user.service.ts
> +  public getAllUser():Promise<any>{
J'ai modifié

2020-03-25 15:20 UTC, glawdysMona commented on skillful_network_client/src/app/shared/services/user.service.ts
> +  public getAllUser():Promise<any>{
J'ai modifié

2020-03-25 15:20 UTC, glawdysMona commented on skillful_network_client/src/app/shared/models/user.ts
> +    this.birthDate= data.birthDate;
J'ai modifié

2020-03-25 15:20 UTC, glawdysMona commented on skillful_network_client/src/app/shared/services/user.service.ts
> +  return this.users[id];
J'ai modifié

2020-03-25 15:29 UTC, danglotb commented on skillful_network_client/src/app/home/users-list/users-list.component.ts
> +    this.userService.findAll().then(res => {
Est-ce qu'on devrait faire cette initialization dans le `ngOnInit()` ?

2020-03-25 15:30 UTC, danglotb requested changes
Retirer l'image du commit avec `git rm <path-to-img>`
Je dirais que l'initialisation des data devrait être faite dans le `ngOnInit()` et pas dans le constructeur du component.

2020-03-26 13:42 UTC, danglotb approved these changes
Tu peux merger une fois que le CI est vert.

2020-03-26 13:47 UTC, merged