Feature/rm 16.3
Bootcamp2020/skillful_network pull request #93
Opened 2020-04-03 10:35 UTC by radhwouna

Ajout des caractéristiques: risque et complexité pour évaluer les offres d'emploi

2020-04-03 11:20 UTC, danglotb commented on skillful_network_client/src/app/home/offre/offre.mock.ts
> +    complexite: string;
Ce serait bien d'avoir le code en anglais :
```ts
risk: string;
complexity: string;
```

Tu peux au passage si tu le souhaite, mettre à jours les autres champs qui sont en français, _e.g._ `competence`.
Mais à voir si ça t'ajoute beaucoup de modification ou non.

2020-04-03 11:20 UTC, danglotb commented on skillful_network_client/src/app/home/offre/offre.ts
> +    private _complexite: string;
Ce serait bien d'avoir le code en anglais :
```ts
risk: string;
complexity: string;
```

Tu peux au passage si tu le souhaite, mettre à jours les autres champs qui sont en français, _e.g._ `competence`.
Mais à voir si ça t'ajoute beaucoup de modification ou non.

2020-04-03 11:20 UTC, danglotb requested changes
Ce serait bien d'avoir le code en anglais :
```ts
risk: string;
complexity: string;
```

Tu peux au passage si tu le souhaite, mettre à jours les autres champs qui sont en français, _e.g._ `competence`.
Mais à voir si ça t'ajoute beaucoup de modification ou non.

2020-04-03 13:25 UTC, danglotb approved these changes

2020-04-03 15:59 UTC, danglotb approved these changes

2020-04-06 15:09 UTC, radhwouna commented
le travail a été déjà fait par une autre personne

2020-04-06 15:09 UTC, closed without merging